Perpustakaan/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perpustakaan.Models;

namespace Perpustakaan.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly PustakaDbContext _context;

        public CategoriesController(PustakaDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaCategory")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaCategory")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Perpustakaan/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perpustakaan.Models;

namespace Perpustakaan.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly PustakaDbContext _context;

        public UsersController(PustakaDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.Username == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Username,Nama,Password,Role,Status")] Users users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(users);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users.FindAsync(id);
            if (users == null)
            {
                return NotFound();
            }
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Username,Nama,Password,Role,Status")] Users users)
        {
            if (id != users.Username)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(users.Username))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.Username == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var users = await _context.Users.FindAsync(id);
            _context.Users.Remove(users);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsersExists(string id)
        {
            return _context.Users.Any(e => e.Username == id);
        }
    }
}

Perpustakaan/Views/Shared/_GetBuku.cshtml
@using System.Linq
@model System.Collections.Generic.List<Book>
<div class="row">
    @if (Model != null && Model.Any())
    {
        foreach (var book in Model)
        {

            <div class="col-md-4">
                <div class="thumbnail" style="height: 450px;" align="center">

                    <a asp-action="DetailBook" asp-route-id="@book.Id">
                        <img src="/images/@book.Gambar" height="250" width="200" />
                    </a>

                    <div class="caption">
                        <h5 style="text-align: center">@book.Judul</h5>
                        <h4 style="text-align: center">@book.Penulis</h4>
                        <h5 style="text-align: center">@book.Penerbit</h5>
                        @{
                            if (book.Status)
                            {
                                <p style="text-align: center">
                                    <a class="btn btn-success" role="button"
                                       data-bukuId="@book.Id"
                                       data-bukuImage="@book.Gambar"
                                       data-bukuJudul="@book.Judul"
                                       data-bukuPenulis="@book.Penulis"
                                       style="margin-top: 10px;">
                                        <span class="glyphicon glyphicon-shopping-cart"></span>  Add To Cart
                                    </a>
                                </p>

                            }
                        }

                    </div>
                </div><br />
            </div>
        }
    }
</div>
<script type="text/javascript">


    $(document)
          .ready(function() {


                $('.btn-success')
                    .click(function() {

                        var selectedProduct = {
                            Id: $(this).attr('data-bukuId'),
                            Gambar: $(this).attr('data-bukuImage'),
                            Judul: $(this).attr('data-bukuJudul'),
                            Penulis: $(this).attr('data-bukuPenulis')
                        };


                        $.ajax({
                            type: 'POST',
                            url: '@Url.Action("AddShoppingCart", "Home")',
                            data: selectedProduct,
                            success: function(response) {
                                alert(response.message );
                                $('#myOrder').text("My Order(" + response.jumlah + ")");
                            },
                            error: function(response) {
                                alert(response.message);
                            }

                        });

                    });


          });
</script>

Perpustakaan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SIM Perpustakaan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/content/site.css" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</head>
<body>
    @RenderSection("scripts", false)

    <div class="navbar navbar-inverse navbar-fixed-top">

        @*detail sintaks lihat pada project lampiran*@
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a asp-controller="Home" asp-action="Index"
                   class="navbar-brand">SIM Perpustakaan</a>
            </div>
            <div class="navbar-collapse collapse">
                <partial name="_Menu" />
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SIM Perpustakaan</p>
        </footer>
    </div>

</body>
</html>

Perpustakaan/Views/Shared/_Menu.cshtml
@using Perpustakaan.Helpers
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{

    var books = HttpContextAccessor.HttpContext.Session.GetObjectFromJson<List<Book>>("ShoppingCart");
    var iChart = 0;
    if (books != null && books.Any())
    {
        iChart = books.Count();
    }
}
@if (User.IsInRole("Admin"))
{
    <ul class="nav navbar-nav">
        <li>
            <a asp-controller="Home" asp-action="DaftarBuku">Daftar Buku</a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="DisplayHistory">History Peminjaman Buku</a>
        </li>
        <li>
            <a id="myOrder" asp-controller="Home" asp-action="DisplayMyOrder">My Order(@iChart)</a>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li class="btn-group nav">
            <button type="button" class="btn navbar-btn"
                    style="background-color:forestgreen">
                @User.Identity.Name
            </button>
            <button type="button"
                    class="btn navbar-btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li> <a asp-controller="Users" asp-action="Index">User</a></li>
                <li> <a asp-controller="Categories" asp-action="Index">Kategori Buku</a></li>
                <li> <a asp-controller="Books" asp-action="Index">Buku</a></li>
                <li> <a asp-controller="Books" asp-action="DaftarPeminjam">Pengembalian Buku</a></li>
                <li> <a asp-controller="Login" asp-action="ChangePassword">Change Password</a></li>
            </ul>
        </li>
        <li>
            <a asp-controller="Login" asp-action="LogOff">
                Log off
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </li>

    </ul>
}
else if (User.IsInRole("Staff"))
{
    <ul class="nav navbar-nav">
        <li>
            <a asp-controller="Home" asp-action="DaftarBuku">Daftar Buku</a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="DisplayHistory">History Peminjaman Buku</a>
        </li>
        <li>
            <a id="myOrder" asp-controller="Home" asp-action="DisplayMyOrder">My Order(@iChart)</a>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li class="btn-group nav">
            <button type="button" class="btn navbar-btn" style="background-color:forestgreen">@User.Identity.Name</button>
            <button type="button" class="btn navbar-btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li> <a asp-controller="Home" asp-action="">Buku</a></li>
                <li> <a asp-controller="Books" asp-action="DaftarPeminjam">Pengembalian Buku</a></li>
                <li> <a asp-controller="Login" asp-action="ChangePassword">Change Password</a></li>
            </ul>
        </li>
        <li>
            <a asp-controller="Login" asp-action="LogOff">
                Log off
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </li>

    </ul>

}
else if (User.IsInRole("General"))
{
    <ul class="nav navbar-nav">
        <li>
            <a asp-controller="Home" asp-action="DaftarBuku">Daftar Buku</a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="DisplayHistory">History Peminjaman Buku</a>
        </li>
        <li>
            <a id="myOrder" asp-controller="Home" asp-action="DisplayMyOrder">My Order(@iChart)</a>
        </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <li class="btn-group nav">
            <button type="button" class="btn navbar-btn" style="background-color:forestgreen">@User.Identity.Name</button>
            <button type="button" class="btn navbar-btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li> <a asp-controller="Login" asp-action="ChangePassword">Change Password</a></li>
            </ul>
        </li>
        <li>
            <a asp-controller="Login" asp-action="LogOff">
                Log off
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </li>

    </ul>
}